In [1]:
import numpy as np
import pandas as pd

In [2]:
flats = pd.read_csv('flats_cleaned.csv')
houses = pd.read_csv('house_cleaned.csv')

In [3]:
# Combines the 'flats' and 'houses' DataFrames into a single DataFrame and resets the index
df = pd.concat([flats,houses],ignore_index=True)

In [4]:
# Shuffles the rows of the DataFrame randomly and resets the index to maintain sequential order
df = df.sample(df.shape[0],ignore_index=True)

In [5]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,12 Bedroom House for sale in Uppals Southend,house,uppal southend,6.75,31915.0,2115.0,Plot area 235(196.49 sq.m.),12,12,3+,others,"Uppals Southend, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address......Uppal southend sector 49 availabl...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,3 BHK Flat in Sector-33 Sohna,flat,godrej nature plus,1.30,8349.0,1557.0,Super Built up area 1557(144.65 sq.m.),3,2,3+,not available,"Sector-33 Sohna, Gurgaon, Haryana",18.0,North,Within 6 months,"['Signature Global Infinity Mall Sohna', 'Bads...",Bang on nh248 highway. Trusted brand.,NaN,"['Intercom Facility', 'Lift(s)', 'Swimming Poo...",NaN
2,2 BHK Flat in Sector 65 Gurgaon,flat,emaar mgf emerald estate,1.30,20602.0,631.0,Super Built up area 1020(94.76 sq.m.)Carpet ar...,2,2,2,study room,"503, Sector 65 Gurgaon, Gurgaon, Haryana",7.0,West,1 to 5 Year Old,"['Sector 53-54 Metro Station', 'Central Plaza ...",This lovely 2 bhk apartment/flat in sector 65 ...,NaN,"['Private Garden / Terrace', 'Lift(s)', 'Maint...","['Green Area4 out of 5', 'Construction4 out of..."
3,3 BHK Flat in Sector 102 Gurgaon,flat,emaar imperial gardens,2.05,9876.0,2076.0,Carpet area: 2025 (188.13 sq.m.),3,4,3+,servant room,"Sector 102 Gurgaon, Gurgaon, Haryana",14.0,South,1 to 5 Year Old,"['Satya The Hive Mall', 'Gurugram Road', 'Dwar...",Important- Not for brokers. Only serious end u...,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
4,2 BHK Flat in Sector 68 Gurgaon,flat,supertech hues,0.82,6950.0,1180.0,Super Built up area 1180(109.63 sq.m.),2,2,3+,others,"Sector-68 Gurgaon, Sector 68 Gurgaon, Gurgaon,...",21.0,NaN,Under Construction,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Residential apartment for sell.The property co...,NaN,"['Intercom Facility', 'Lift(s)', 'Feng Shui / ...","['Environment4 out of 5', 'Safety5 out of 5', ..."

In [6]:
df.to_csv('gurgaon_properties.csv',index=False)